# Generated by Django 3.1.4 on 2021-02-10 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_delete_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.BooleanField(default=False)),
                ('subject', models.CharField(choices=[('En', 'English'), ('M', 'Maths'), ('PE', 'PE'), ('His', 'History'), ('Bio', 'Biology'), ('Ph', 'Physics')], max_length=10)),
                ('form_teacher', models.CharField(blank=True, default=None, max_length=5)),
                ('form', models.ManyToManyField(related_name='teacher_classes', to='accounts.Form_Cl')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
