# Generated by Django 3.1.4 on 2021-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teacher', '0004_remove_teacher_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teacher_classes', to='students.Classes'),
        ),
    ]
