# Generated by Django 3.1.4 on 2021-02-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teacher', '0005_teacher_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('En', 'English'), ('M', 'Maths'), ('PE', 'PE'), ('His', 'History'), ('Bio', 'Biology'), ('Ph', 'Physics')], max_length=10)),
                ('grade', models.IntegerField(choices=[(1, 'F'), (2, 'E'), (3, 'D'), (4, 'C'), (5, 'B'), (6, 'A')])),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
