# Generated by Django 3.1.4 on 2021-02-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'F'), (2, 'E'), (3, 'D'), (4, 'C'), (5, 'B'), (6, 'A')]),
        ),
    ]
