# Generated by Django 3.1.4 on 2021-02-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teacher', '0007_auto_20210212_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='classes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.classes'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='desc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tests',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='subject',
            field=models.CharField(blank=True, choices=[('En', 'English'), ('M', 'Maths'), ('PE', 'PE'), ('His', 'History'), ('Bio', 'Biology'), ('Ph', 'Physics')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tests',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
