# Generated by Django 3.1.4 on 2021-02-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20210212_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tests',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='planned',
            field=models.DateTimeField(null=True),
        ),
    ]
