# Generated by Django 3.1.4 on 2021-02-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20210214_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
