# Generated by Django 3.1.4 on 2021-02-10 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210210_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Cl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('subject', models.CharField(choices=[('En', 'English'), ('M', 'Maths'), ('PE', 'PE'), ('His', 'History'), ('Bio', 'Biology'), ('Ph', 'Physics')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.BooleanField(default=False)),
                ('subject', models.CharField(choices=[('En', 'English'), ('M', 'Maths'), ('PE', 'PE'), ('His', 'History'), ('Bio', 'Biology'), ('Ph', 'Physics')], max_length=10)),
                ('form_teacher', models.CharField(default=None, max_length=5)),
                ('form', models.ManyToManyField(related_name='teacher_classes', to='accounts.Form_Cl')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='form_cl',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
