# Generated by Django 3.1.4 on 2021-02-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_form_cl_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_cl',
            name='students',
        ),
        migrations.AddField(
            model_name='form_cl',
            name='students',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
    ]
