# Generated by Django 3.1.4 on 2021-02-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210210_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
