# Generated by Django 3.1.4 on 2021-02-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210211_0954'),
        ('accounts', '0006_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Form_Cl',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
